### ISSUE TITLE
"Why HTTP Bots" on Docs

### ISSUE THREAD

**Issue by thewilloftheshadow** [buape/carbon#102]
Add a page about why HTTP bots are a thing, and how they're useful over gateway bots.

**Comment by Xanderxx69** [comment]
Is that what this page is meant to be? 
![image](https://github.com/user-attachments/assets/6b5b620b-0bb6-420b-a71f-95f6b16c0963)

**Comment by thewilloftheshadow** [comment]
No that’s different, that page is about why Carbon is based around extending classes
